[package]
name = "foo"
version = "0.0.0"

[lib]
path = "rust/api/resource_name.rs"

[dependencies]
argh = "0.1.10"
async-trait = "0.1.68"
bytes = "1.4.0"
futures-util = "0.3.28"
futures-lite = "1.13.0"
glommio = "0.8.0"
heck = "0.4.1"
http = "0.2.9"
http-body = "0.4.5"
prost = "0.12.0"
prost-build = "0.12.0"
prost-types = "0.12.0"
sled = "0.34.7"
tonic-build = "0.10.1"
tonic-health = "0.10.1"
tonic-types = "0.10.1"

[dependencies.foundationdb]
default-features = false
features = [
  "fdb-7_1",
  "embedded-fdb-include"
]
version = "0.7.0"

[dependencies.hyper]
features = ["http2", "server"]
version = "0.14.26"

[dependencies.prost-reflect]
features = ["text-format"]
version = "0.12.0"

[dependencies.smallvec]
features = ["const_generics", "union"]
version = "1.10.0"

[dependencies.tokio]
features = ["macros"]
version = "1.28.1"

[dependencies.tonic]
default-features = false
features = [
  "prost",
  "codegen",
  "transport",
]
version = "0.10.1"

[dependencies.tower]
default-features = false
features = [
  "load-shed",
]
version = "0.4.13"

[dependencies.uuid]
features = ["v7"]
version = "1.3.2"

[dev-dependencies]
mockall = "0.11.4"
